name = "DojoLight"
uuid = "bdc523a3-80b0-4a87-8eb5-2d907b6237e8"
authors = ["simon-lc <simonlc@stanford.edu>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
DirectTrajectoryOptimization = "a9f42406-efe7-414c-8b71-df971cc98041"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Mehrotra = "ff64e54f-29a3-40c0-a3ca-0c9552343258"
MeshCat = "283c5d60-a78f-5afe-a0af-af636b173e11"
Meshing = "e6723b4c-ebff-59f1-b4b7-d97aa5274f73"
Nonconvex = "01bcebdf-4d21-426d-b5c4-6132c1619978"
NonconvexIpopt = "bf347577-a06d-49ad-a669-8c0e005493b8"
NonconvexPercival = "4296f080-e499-44ba-a02c-ae40015c44d5"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Polyhedra = "67491407-f73d-577b-9b50-8179a7c68029"
Quaternions = "94ee1d12-ae83-5a48-8b1c-48b8ff168ae0"
RobotVisualizer = "72694564-f60b-4882-9057-f9f0ff647ee8"
