[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GraphRecipes = "bd48cda9-67a9-57be-86fa-5b3c104eda73"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
IterativeLQR = "605048dd-e178-462b-beb9-98a09398ef27"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
MeshCatMechanisms = "6ad125db-dd91-5488-b820-c1df6aab299d"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RigidBodyDynamics = "366cf18f-59d5-5db9-a4de-86a9f6786172"
RobotVisualizer = "72694564-f60b-4882-9057-f9f0ff647ee8"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
